practica=(15,18,17,16)
suma=sum(practica)
promedio = suma / len(practica)
print(F"La cantidad de valores en la tupla : \t"  +str(practica) +"\t"+"\n" + "\t"+str(len(practica)))
print(f"El primero valor de la tupla: \t" + str(practica) +  "\n" +"\t" + str(practica[0]))
print(f"El ultimo valor de la tupla usando len es: \t"+ str(practica) +"\n" + "\t" + str(practica[len(practica)-1]))
print(f"El ultimo valor de la tupla usando el indice negativo: \t"+ str(practica) + "\n" + "\t"+ str(practica[-1]))
print(f"Un slice o porcion de las posiciones 1 y 2 son: \t" + str(practica) + "\n" + "\t" +str(practica[1:3]))
print(f"El promedio de las notas almecendas en la tupla es: \t"+ str(practica) + "\n" +"\t" +str(promedio))
